spring:
  datasource:
    druid:
      url: jdbc:mysql://123.56.194.247:3306/blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
      username: root
      password: qzy123
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 10000
      testOnBorrow: true
      testOnReturn: false
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  redis:
    host: 123.56.194.247
    port: 6379
    password: qzy123888
  application:
    name: blog
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.jg
  configuration:
    map-underscore-to-camel-case: true

fdfs:
  so-timeout: 2500
  connect-timeout: 1000
  thumb-image:
    width: 100
    height: 100
  tracker-list:
    - 123.56.194.247:22122
upload:
  base-url: http://123.56.194.247:8888
  allow-types:
    - image/jpeg
    - image/png
    - image/bmp
    - image/gif
    - audio/mp3
    - audio/mpeg